development:
  dialect: "mysql"
  database: "category"
  port: "3306"
  user: "sodadb"
  password: "XCF45!"
  host: "mobilebuildmaster.local"
  
test:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/src/github.com/branohricardo/workshop-category-microservice/workshop-category-microservice_test.sqlite

production:
  dialect: "sqlite3"
  database: {{env "GOPATH" }}/src/github.com/branohricardo/workshop-category-microservice/workshop-category-microservice_production.sqlite